- .github/workflows/build.yml
I don't know how to test this locally but should work
> Add GitHub CI to verify if builds succeed

- src/main/kotlin/io/github/dockyardmc/player/Player.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundPlayerAbilitiesPacket.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundPickItemPacket.kt
Implements block picking and adds gamemode parameter to ClientboundPlayerAbilitiesPacket
> Implement PickBlock

- src/main/kotlin/io/github/dockyardmc/Main.kt
- src/main/kotlin/io/github/dockyardmc/player/Player.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundEntityInteractPacket.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundUseItemOnPacket.kt
- src/main/kotlin/io/github/dockyardmc/utils/InteractionTimeout.kt
- src/main/kotlin/io/github/dockyardmc/utils/Utils.kt
Fixes Interaction events being fired twice because minecraft is stupid and sends the packet twice
> Fix interaction events being fired twice

- src/main/kotlin/io/github/dockyardmc/DockyardServer.kt
- src/main/kotlin/io/github/dockyardmc/events/PacketReceivedEvent.kt
- src/main/kotlin/io/github/dockyardmc/events/PacketSentEvent.kt
- src/main/kotlin/io/github/dockyardmc/extentions/ExtendedConnection.kt
- src/main/kotlin/io/github/dockyardmc/player/Player.kt
- src/main/kotlin/io/github/dockyardmc/player/PlayerManager.kt
- src/main/kotlin/io/github/dockyardmc/protocol/PacketProcessor.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/configurations/ConfigurationHandler.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/handshake/HandshakeHandler.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/login/LoginHandler.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundPlayerSwingHandPacket.kt
This also adds `PacketProcessor.getPlayerOrNull()`,
`PacketProcessor.getPlayerOrThrow()` and
`PacketProcessor.isPlayerInitialized()`
> add processor field to packet events

- src/main/kotlin/io/github/dockyardmc/blocks/BarrelPlacementRules.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundUseItemOnPacket.kt
Fixes barrel not having placement rules
> Fix barrel placement

- src/main/kotlin/io/github/dockyardmc/protocol/packets/configurations/ConfigurationHandler.kt
Before: ![before](https://github.com/user-attachments/assets/40db12ff-1a2a-4033-96f9-c4ab71949a30)
After: ![after](https://github.com/user-attachments/assets/3e5cfe4f-5588-4954-b5a5-82eec68911e8)
thnx :3
> fix: reset styling after server brand

- src/main/kotlin/io/github/dockyardmc/Main.kt
- src/main/kotlin/io/github/dockyardmc/events/system/EventFilter.kt
- src/main/kotlin/io/github/dockyardmc/events/system/EventSystem.kt
- src/main/kotlin/io/github/dockyardmc/events/system/HandlerList.kt
- src/main/kotlin/io/github/dockyardmc/utils/DebugScoreboard.kt
A couple things:
- makes things related to modifying event listeners Synchronised to hopefully fix async issues
- fixed weird behaviour when registering listeners in listeners
- made global events always bypass filter cuz it was stupid the way i did it before
> Event System Fixes

- src/main/kotlin/io/github/dockyardmc/inventory/EntityInventory.kt
- src/main/kotlin/io/github/dockyardmc/world/World.kt
> fix(events): dispatch InventoryItemChangeEvent

- src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
> Add eye height location

- src/main/kotlin/io/github/dockyardmc/entity/handlers/EntityItemPickupHandler.kt
- src/main/kotlin/io/github/dockyardmc/events/EntityPickupItemEvent.kt
> Add `itemDropEntity` field to the `EntityPickupItemEvent` event

- src/main/kotlin/io/github/dockyardmc/entity/ai/AIManager.kt
Fix to where even if entity is disposed, you would have no way of disposing the AIManager of the entity
> Make AIManager disposable

- src/main/kotlin/Main.kt
- src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
- src/main/kotlin/io/github/dockyardmc/location/Location.kt
- src/main/kotlin/io/github/dockyardmc/maths/vectors/Vector3d.kt
- src/main/kotlin/io/github/dockyardmc/player/Player.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundSetEntityVelocityPacket.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundSpawnEntityPacket.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundClientInputPacket.kt
- src/main/kotlin/io/github/dockyardmc/utils/Velocity.kt
Adds way to set player velocity. **Not ADD  SET** there is no way to get velocity of player. The client doesn't send it and I dont feel like simulating it
> Add way to set player velocity

- src/main/kotlin/io/github/dockyardmc/apis/bossbar/Bossbar.kt
> Fix bossbar not removing viewers when they leave

- src/main/kotlin/Main.kt
- src/main/kotlin/io/github/dockyardmc/location/Location.kt
- src/test/kotlin/io/github/dockyard/tests/location/HighestLowestPointTest.kt
> add way to get nearest highest, lowest points

- .idea/inspectionProfiles/Project_Default.xml
- .idea/structuralSearch.xml
- src/main/kotlin/Main.kt
- src/main/kotlin/io/github/dockyardmc/maths/MathUtils.kt
- src/main/kotlin/io/github/dockyardmc/maths/counter/AnimationProvider.kt
- src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounter.kt
- src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounterDouble.kt
- src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounterFloat.kt
- src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounterInt.kt
- src/main/kotlin/io/github/dockyardmc/maths/counter/RollingCounterLong.kt
- src/main/kotlin/io/github/dockyardmc/registry/registries/BlockRegistry.kt
- src/main/kotlin/io/github/dockyardmc/scheduler/AsyncSchedulerTask.kt
- src/main/kotlin/io/github/dockyardmc/scheduler/GlobalScheduler.kt
- src/main/kotlin/io/github/dockyardmc/scheduler/Scheduler.kt
- src/main/kotlin/io/github/dockyardmc/world/palette/AdaptivePalette.kt
- src/main/kotlin/io/github/dockyardmc/world/palette/PaletteWriter.kt
> Add `RollingCounter` util class

- src/main/kotlin/io/github/dockyardmc/apis/Hologram.kt
- src/main/kotlin/io/github/dockyardmc/entity/DisplayEntity.kt
- src/main/kotlin/io/github/dockyardmc/entity/ElderGuardian.kt
- src/main/kotlin/io/github/dockyardmc/entity/Entity.kt
- src/main/kotlin/io/github/dockyardmc/entity/Guardian.kt
- src/main/kotlin/io/github/dockyardmc/entity/InteractionEntity.kt
- src/main/kotlin/io/github/dockyardmc/entity/ItemDropEntity.kt
- src/main/kotlin/io/github/dockyardmc/entity/Parrot.kt
- src/main/kotlin/io/github/dockyardmc/entity/Ravager.kt
- src/main/kotlin/io/github/dockyardmc/entity/Squid.kt
- src/main/kotlin/io/github/dockyardmc/entity/TestZombie.kt
- src/main/kotlin/io/github/dockyardmc/entity/Warden.kt
- src/main/kotlin/io/github/dockyardmc/inventory/PlayerInventory.kt
- src/main/kotlin/io/github/dockyardmc/npc/PlayerNpc.kt
- src/main/kotlin/io/github/dockyardmc/player/Player.kt
`var` kinda defeats the purpose of a bindable
> Change a couple of bindables from var to val

- src/main/kotlin/io/github/dockyardmc/protocol/packets/handshake/ServerboundPingRequestPacket.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/clientbound/ClientboundPlayPingResponsePacket.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundPlayPingRequestPacket.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/registry/ServerPacketRegistry.kt
- **fix: ping response (handshake) should return same timestamp**
- **feat: added serverbound ping request (play) packet**
> Fix ping packets

- src/main/kotlin/io/github/dockyardmc/DockyardServer.kt
- src/main/kotlin/io/github/dockyardmc/player/Player.kt
- src/main/kotlin/io/github/dockyardmc/world/World.kt
> fix `world.join` not ensuring player gets properly teleported to intended location

- src/main/kotlin/io/github/dockyardmc/player/Player.kt
- src/test/kotlin/io/github/dockyard/tests/events/ServerSendPlayerMessageEventTest.kt
> Fix `player.sendSystemMessage` raising `ServerSendPlayerMessageEvent`

- src/main/kotlin/io/github/dockyardmc/data/DataComponentPatch.kt
- src/main/kotlin/io/github/dockyardmc/data/components/ConsumableComponent.kt
- src/main/kotlin/io/github/dockyardmc/events/PlayerCancelledConsumingEvent.kt
- src/main/kotlin/io/github/dockyardmc/events/PlayerConsumeItemTickEvent.kt
- src/main/kotlin/io/github/dockyardmc/events/PlayerFinishConsumingEvent.kt
- src/main/kotlin/io/github/dockyardmc/events/PlayerStartConsumingEvent.kt
- src/main/kotlin/io/github/dockyardmc/player/systems/FoodEatingSystem.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundPlayerActionPacket.kt
- src/main/kotlin/io/github/dockyardmc/protocol/packets/play/serverbound/ServerboundUseItemPacket.kt
- src/test/kotlin/io/github/dockyard/tests/events/PlayerCancelConsumingEventTest.kt
- src/test/kotlin/io/github/dockyard/tests/events/PlayerConsumeTickEventTest.kt
- src/test/kotlin/io/github/dockyard/tests/events/PlayerFinishConsumingEventTest.kt
- src/test/kotlin/io/github/dockyard/tests/events/PlayerStartConsumingEventTest.kt
> Fix consumable components being always treated as food

- src/main/kotlin/io/github/dockyardmc/protocol/packets/configurations/ConfigurationHandler.kt
- src/main/kotlin/io/github/dockyardmc/resourcepack/ResourcepackManager.kt
> Make ConfigurationHandler send queued up resourcepacks only when player enters configuration
